export enum Languages {
    BG = "BG",
    CS = "CS",
    DA = "DA",
    DE = "DE",
    EL = "EL",
    ES = "ES",
    FI = "FI",
    JA = "JA",
    FR = "FR",
    HU = "HU",
    ID = "ID",
    IT = "IT",
    NL = "NL",
    PL = "PL",
    PT_BR = "PT-BR",
    PT_PT = "PT-PT",
    RU = "RU",
    SV = "SV",
    TR = "TR",
    UK = "UK",
    ZH = "ZH",
}
