import {transformValues} from "../services/fetch-and-process";

export const DefaultPlanets = [
    {
        disc_year: 2018,
        pl_desc: "Pi Mensae c is a Neptune-like exoplanet that orbits an F-type star. Its mass is 4.82 Earths, it takes 6.3 days to complete one orbit of its star, and is 0.06839 AU from its star. Its discovery was announced in 2018.",
        pl_eqt: 874,
        pl_eqt_f: 1605,
        pl_masse: 4.52,
        pl_name: "pi Men c",
        pl_orbper: 6,
        pl_rade: 2.06,
        pl_refname: "<a refstr=GANDOLFI_ET_AL__2018 href=https://ui.adsabs.harvard.edu/abs/2018A&A...619L..10G/abstract target=ref>Gandolfi et al. 2018</a>",
        pl_subtitle: "A Neptune-like gas giant planet",
        pl_type: "Neptune-like",
        sy_dist: 60,
        sy_snum: 1
    },
    {
        disc_year: 2005,
        pl_desc: "HD 149026 b is a gas giant exoplanet that orbits an F-type star. Its mass is 0.38 Jupiters, it takes 2.9 days to complete one orbit of its star, and is 0.04364 AU from its star. Its discovery was announced in 2005.",
        pl_eqt: 1361,
        pl_eqt_f: 2482,
        pl_masse: 114.1,
        pl_name: "HD 149026 b",
        pl_orbper: 3,
        pl_rade: 7.33,
        pl_refname: "<a refstr=TORRES_ET_AL__2008 href=https://ui.adsabs.harvard.edu/abs/2008ApJ...677.1324T/abstract target=ref> Torres et al. 2008 </a>",
        pl_subtitle: "A giant planet composed mainly of gas",
        pl_type: "Gas Giant",
        sy_dist: 247,
        sy_snum: 1
    },
    {
        disc_year: 2010,
        pl_desc: "CoRoT-11 b is a gas giant exoplanet that orbits an F-type star. Its mass is 2.33 Jupiters, it takes 3 days to complete one orbit of its star, and is 0.0436 AU from its star. Its discovery was announced in 2010.",
        pl_eqt: 1462,
        pl_eqt_f: 2663,
        pl_masse: 743.72,
        pl_name: "CoRoT-11 b",
        pl_orbper: 3,
        pl_rade: 15.98,
        pl_refname: "<a refstr=SOUTHWORTH_2011 href=https://ui.adsabs.harvard.edu/abs/2011MNRAS.417.2166S/abstract target=ref>Southworth 2011</a>",
        pl_subtitle: "A giant planet composed mainly of gas",
        pl_type: "Gas Giant",
        sy_dist: 2136,
        sy_snum: 1
    },
    {
        disc_year: 2020,
        pl_desc: "TOI-677 b is a gas giant exoplanet that orbits an F-type star. Its mass is 1.236 Jupiters, it takes 11.2 days to complete one orbit of its star, and is 0.1038 AU from its star. Its discovery was announced in 2020.",
        pl_eqt: 979,
        pl_eqt_f: 1794,
        pl_masse: 392.84,
        pl_name: "TOI-677 b",
        pl_orbper: 11,
        pl_rade: 13.12,
        pl_refname: "<a refstr=JORD_AACUTE_N_ET_AL__2020 href=https://ui.adsabs.harvard.edu/abs/2020AJ....159..145J/abstract target=ref>Jord&aacute;n et al. 2020</a>",
        pl_subtitle: "A giant planet composed mainly of gas",
        pl_type: "Gas Giant",
        sy_dist: 463,
        sy_snum: 1
    },
    {
        disc_year: 2020,
        pl_desc: "EPIC 249893012 d is a Neptune-like exoplanet that orbits a G-type star. Its mass is 10.18 Earths, it takes 35.7 days to complete one orbit of its star, and is 0.22 AU from its star. Its discovery was announced in 2020.",
        pl_eqt: 479,
        pl_eqt_f: 894,
        pl_masse: 10.18,
        pl_name: "EPIC 249893012 d",
        pl_orbper: 36,
        pl_rade: 3.94,
        pl_refname: "<a refstr=HIDALGO_ET_AL__2020 href=https://ui.adsabs.harvard.edu/abs/2020A&A...636A..89H/abstract target=ref>Hidalgo et al. 2020</a>",
        pl_subtitle: "A Neptune-like gas giant planet",
        pl_type: "Neptune-like",
        sy_dist: 1048,
        sy_snum: 1
    },
    {
        disc_year: 2017,
        pl_desc: "GJ 9827 c is a super Earth exoplanet that orbits a K-type star. Its mass is 0.84 Earths, it takes 3.6 days to complete one orbit of its star, and is 0.03925 AU from its star. Its discovery was announced in 2017.",
        pl_eqt: 538,
        pl_eqt_f: 1000,
        pl_masse: 2.42,
        pl_name: "GJ 9827 c",
        pl_orbper: 4,
        pl_rade: 1.27,
        pl_refname: "<a refstr=RODRIGUEZ_ET_AL__2018 href=https://ui.adsabs.harvard.edu/abs/2018AJ....155...72R/abstract target=ref>Rodriguez et al. 2018</a>",
        pl_subtitle: "A potentially rocky world, larger than Earth",
        pl_type: "Super Earth",
        sy_dist: 97,
        sy_snum: 1
    },{
        disc_year: 2012,
        pl_desc: "Kepler-36b and its companion planet, Kepler-36c, are far too close to their sun to be in the habitable zone, but they are bizarrely close to each other.",
        pl_eqt: 705,
        pl_eqt_f: 1301,
        pl_masse: 4.45,
        pl_name: "Kepler-36 b",
        pl_orbper: 14,
        pl_rade: 1.49,
        pl_refname: "<a refstr=CARTER_ET_AL__2012 href=https://ui.adsabs.harvard.edu/abs/2012Sci...337..556C/abstract target=ref> Carter et al. 2012 </a>",
        pl_subtitle: "A super-Earth with a super-close neighbor",
        pl_type: "Super Earth",
        sy_dist: 1722,
        sy_snum: 1
    },{
        disc_year: 2015,
        pl_desc: "K2-18 b is a super Earth exoplanet that orbits an M-type star. Its mass is 8.92 Earths, it takes 32.9 days to complete one orbit of its star, and is 0.1429 AU from its star. Its discovery was announced in 2015.",
        pl_eqt: -38,
        pl_eqt_f: -37,
        pl_masse: 7.96,
        pl_name: "K2-18 b",
        pl_orbper: 33,
        pl_rade: 2.38,
        pl_refname: "<a refstr=CLOUTIER_ET_AL__2017 href=https://ui.adsabs.harvard.edu/abs/2017A&A...608A..35C/abstract target=ref>Cloutier et al. 2017</a>",
        pl_subtitle: "A potentially rocky world, larger than Earth",
        pl_type: "Super Earth",
        sy_dist: 124,
        sy_snum: 1
    },{
        disc_year: 2016,
        pl_desc: "K2-66 b is a super Earth exoplanet that orbits a G-type star. Its mass is 21.3 Earths, it takes 5.1 days to complete one orbit of its star, and is 0.05983 AU from its star. Its discovery was announced in 2016.",
        pl_eqt: 1099,
        pl_eqt_f: 2010,
        pl_masse: 21.3,
        pl_name: "K2-66 b",
        pl_orbper: 5,
        pl_rade: 2.49,
        pl_refname: "<a refstr=SINUKOFF_ET_AL__2017 href=https://ui.adsabs.harvard.edu/abs/2017AJ....153..271S/abstract target=ref>Sinukoff et al. 2017</a>",
        pl_subtitle: "A potentially rocky world, larger than Earth",
        pl_type: "Super Earth",
        sy_dist: 1676,
        sy_snum: 1
    },
    {
        disc_year: 2014,
        pl_desc: "Kepler-107 b is a super Earth exoplanet that orbits a G-type star. Its mass is 3.51 Earths, it takes 3.2 days to complete one orbit of its star, and is 0.04544 AU from its star. Its discovery was announced in 2014.",
        pl_eqt: 1320,
        pl_eqt_f: 2408,
        pl_masse: 3.51,
        pl_name: "Kepler-107 b",
        pl_orbper: 3,
        pl_rade: 1.54,
        pl_refname: "<a refstr=BONOMO_ET_AL__2019 href=https://ui.adsabs.harvard.edu/abs/2019NatAs...3..416B/abstract target=ref>Bonomo et al. 2019</a>",
        pl_subtitle: "A potentially rocky world, larger than Earth",
        pl_type: "Super Earth",
        sy_dist: 1716,
        sy_snum: 1
    }
];
